### PR TITLE
fix icon links

### PR DESCRIPTION
**Pull request by sithlord48**
Use a QTextBrowser so the icon links are clickable and open in a browser.

### CODE REVIEW

**Comment by berviantoleo** [comment]
Please check the error build from the CI @sithlord48

**Review by berviantoleo — CHANGES_REQUESTED** [review]
Build failed, need fix.

**Comment by sithlord48** [comment]
I have to check what changed in the Qt version the build service is using and my local one.

**Comment by sithlord48** [comment]
Seams the newer version of creator set the markdown property for any html you put in automaticly. I have corrected the error and it should build just fine now.

**Review by berviantoleo — APPROVED** [review]
Thank you so much for your effort.

**Pull request merged**
