### PR TITLE
Fix buttons

### PR DESCRIPTION
**Pull request by sithlord48**
Requires : https://github.com/berv-uni-project/Frog-Archiver/pull/30.

Allow the buttons to be sized based on their contents size.

### CODE REVIEW

**Review by berviantoleo — COMMENTED** [review]
I'm not test this before, but can I know the result? Be better if have a padding or margins.

**Review by berviantoleo — CHANGES_REQUESTED** [review]
I think be better if have kind padding or margin into this button

**Comment by sithlord48** [comment]
The buttons can now fit the contents and are not longer bound to a small maximum size. This was causing an issue on Hi-DPI

Before: 
2019-10-01_Frog Archiver_1

After: 
2019-10-01_Frog Archiver_1-1

**Comment by berviantoleo** [comment]
Ok, looking good. Thanks!

**Review by berviantoleo — APPROVED** [review]

**Pull request merged**
